INSERT INTO `departments` (`department_id`, `name`, `description`) VALUES
(1, 'Electrónicos', 'Todo lo relacionado con tecnología y dispositivos electrónicos.'),
(2, 'Electrodomésticos', 'Electrodomésticos para el hogar.'),
(3, 'Cocinas', 'Cocinas para preparar alimentos.'),
(4, 'Refrigeradores', 'Refrigeradores para conservar alimentos.'),
(5, 'Lavadoras', 'Lavadoras para el cuidado de la ropa.'),
(6, 'Tecnología Móvil', 'Dispositivos móviles y accesorios.'),
(7, 'Teléfonos', 'Teléfonos móviles de diversas marcas.'),
(8, 'Tabletas', 'Tabletas para entretenimiento y trabajo.'),
(9, 'Accesorios Móviles', 'Fundas, cargadores y otros accesorios móviles.'),
(10, 'Electrónica de Consumo', 'Gadgets y dispositivos electrónicos para uso diario.'),
(11, 'Televisores', 'Televisores de diferentes tamaños y tecnologías.'),
(12, 'Audio y Video', 'Equipos de audio y video para entretenimiento.'),
(13, 'Cámaras y Fotografía', 'Cámaras y accesorios para la fotografía.'),
(14, 'Cámaras Digitales', 'Cámaras digitales para capturar momentos.'),
(15, 'Accesorios de Fotografía', 'Lentes, trípodes y otros accesorios fotográficos.'),
(16, 'Videojuegos', 'Consolas y videojuegos de diversas plataformas.'),
(17, 'Consolas', 'Consolas de videojuegos populares.'),
(18, 'Juegos', 'Juegos para diferentes consolas y plataformas.'),
(19, 'Accesorios para Videojuegos', 'Controles, headsets y otros accesorios.'),
(20, 'Música', 'Instrumentos musicales y equipos de audio.'),
(21, 'Instrumentos Musicales', 'Instrumentos para músicos de todos los niveles.'),
(22, 'Equipos de Audio', 'Altavoces y sistemas de sonido.'),
(23, 'Ropa', 'Vestimenta para hombres, mujeres y niños.'),
(24, 'Ropa Deportiva', 'Vestimenta especializada para actividades deportivas.'),
(25, 'Calzado Deportivo', 'Calzado diseñado para el deporte.'),
(26, 'Accesorios Deportivos', 'Artículos complementarios para deportes.'),
(27, 'Ropa Casual', 'Vestimenta informal para el día a día.'),
(28, 'Vestidos', 'Vestidos para diferentes ocasiones.'),
(29, 'Camisetas', 'Camisetas para hombres, mujeres y niños.'),
(30, 'Accesorios de Moda', 'Bolsos, joyas y otros complementos.'),
(31, 'Hogar y Muebles', 'Muebles y artículos para el hogar.'),
(32, 'Muebles', 'Muebles de diversas categorías.'),
(33, 'Sofás', 'Sofás y sillones para la sala.'),
(34, 'Mesas', 'Mesas de comedor y de centro.'),
(35, 'Sillas', 'Sillas para diferentes usos.'),
(36, 'Artículos de Limpieza', 'Productos de limpieza para el hogar.'),
(37, 'Jardinería', 'Plantas y herramientas para el jardín.'),
(38, 'Plantas', 'Plantas decorativas y de interior.'),
(39, 'Herramientas de Jardín', 'Herramientas para cuidar el jardín.'),
(40, 'Cocina', 'Utensilios y accesorios para la cocina.'),
(41, 'Utensilios', 'Utensilios esenciales para cocinar.'),
(42, 'Electrodomésticos de Cocina', 'Electrodomésticos para facilitar la cocina.'),
(43, 'Alimentos y Bebidas', 'Productos alimenticios y bebidas.'),
(44, 'Alimentos Frescos', 'Frutas y verduras frescas.'),
(45, 'Bebidas', 'Bebidas alcohólicas y no alcohólicas.'),
(46, 'Bebidas Alcohólicas', 'Bebidas con contenido Alcohólico'),
(47, 'Bebidas No Alcohólicas', 'Bebidas sin alcohol'),
(48, 'Salud y Belleza', 'Productos de cuidado personal y belleza.'),
(49, 'Cuidado Personal', 'Artículos para la higiene y el cuidado personal.'),
(50, 'Productos para el Cabello', 'Champús, acondicionadores y tratamientos.'),
(51, 'Productos para la Piel', 'Cremas y lociones para el cuidado de la piel.'),
(52, 'Salud y Bienestar', 'Suplementos y productos de bienestar.'),
(53, 'Suplementos', 'Suplementos de Salud'),
(54, 'Productos Naturales', 'Productos Naturistas'),
(55, 'Cuidado del Bebé', 'Productos y accesorios para bebés.'),
(56, 'Alimentos para Bebés', 'Comida y fórmulas para bebés.'),
(57, 'Accesorios para Bebés', 'Artículos para la comodidad de los bebés.'),
(58, 'Juguetes', 'Juguetes y juegos para niños.'),
(59, 'Juguetes Educativos', 'Juguetes que fomentan el aprendizaje.'),
(60, 'Juguetes para Bebés', 'Juguetes diseñados para los más pequeños.'),
(61, 'Juguetes de Construcción', 'Juguetes que estimulan la creatividad.'),
(62, 'Deportes y Aire Libre', 'Equipamiento deportivo y artículos para actividades al aire libre.'),
(63, 'Equipos Deportivos', 'Equipamiento para diversos deportes.'),
(64, 'Ropa de Camping', 'Vestimenta adecuada para actividades al aire libre.'),
(65, 'Accesorios de Pesca', 'Artículos para la pesca recreativa.'),
(66, 'Automotriz', 'Accesorios y productos para automóviles.'),
(67, 'Accesorios para Automóviles', 'Artículos para mejorar la experiencia automotriz.'),
(68, 'Herramientas para Automóviles', 'Herramientas para el mantenimiento de vehículos.'),
(69, 'Libros y Papelería', 'Libros, material de oficina y artículos de papelería.'),
(70, 'Libros', 'Libros de diferentes géneros.'),
(71, 'Ficción', 'Novelas y cuentos de ficción.'),
(72, 'No Ficción', 'Libros de historia, biografías y más.'),
(73, 'Material de Oficina', 'Artículos para el trabajo en oficina.'),
(74, 'Papelería', 'Útiles escolares y de oficina.'),
(75, 'Productos para Mascotas', 'Alimentos y accesorios para mascotas.'),
(76, 'Alimentos para Mascotas', 'Comida para perros, gatos y otros animales.'),
(77, 'Accesorios para Mascotas', 'Juguetes y accesorios para el cuidado de mascotas.'),
(78, 'Juguetes para Mascotas', 'Juguetes diseñados para entretener a las mascotas.');

